### PR TITLE
Backend lrc search coverage fix

### LINKED ISSUE #29: LRC Endpoint Service Separation
Refactor LRC code to consolidate the service more so endpoint only calls one service function due to the fact they are currently dependently chained. Need separate endpoints in the future for due + artist req, and no artist req,.

### LINKED ISSUE #52: LRC Endpoint Business Logic
Write another service function to migrate that controller logic to the service side, instead of controller making two calls.
This is so integrated service doesn't have to make two calls either. Refactor both, this is denoted with issue number in the file

### LINKED ISSUE #55: Search enhancement for integration
Do multiple queries on LRC lyrics with different key words, title, artist, as of now, the integration only uses the title and artist from genius which can be assumed to be the most correct, but sometimes genius has formatting on the artist name that might not correlate well with LRC's search, perhaps we can also use the user's input, and also potentially do secondhand processing on genius's artist title for implications to see if we can get results from LRC. User entries can maybe be logged into the song model (alternate artists section) or perhaps have a separate section for user voted stuff, and if multiple people search the same thing, we can have multiple entries, counted by dictionary to see popular artist name formats that user searches with. I believe LRC lib takes public contribution to lyrics, so this could match with the public opinion on how artist names should be spelled?

### PR DESCRIPTION
**Pull request by darint916**
# 🚀 Pull Request

## 📋 Summary

Refactored the entire of LRC lyrics to use both endpoints from LRCLIB and then to do multiple queries to maximize chances of a match due to song name inconsistencies. Did word extraction to potentially help find match as last resort. Also added exact matching to increase accuracy of main match. Did fuzzy ordering + duration tolerance for better ordering on first song hits for romanization and such. Determined matching after messing around with LRCLIB's matching and prioritizing for their search endpoint

Mainly cleaned up the endpoint to make it much more flexible and simple. 

## 🔍 Related Issues

Fixes #52  
Fixes #29 
Fixes #55 

## 📷 Screenshots (if applicable)

Example1 :
Search for this previously had mismatched romanization artist with the original artist. 
New search style, actually this find the exact match for title + artist, and then uses those as sources of truth to find romanization or similar title/artist using fuzzy match with threshold. Each call took about 0.48seconds. 
image

image

Full romanization exact match:
image
image

Partial title match:
image

album search:
image
image

duration accuracy:
image
image

youtube name matches:
image

Keyword extraction success:
Formed new query string only with keywords automatically (look at q parameters)
image
image

New Artist match tuning, might want to tune in the future and have a dataset to match against as a unit test to make sure tuning doesn't fail artists. As you can see, we need at least 2/3 for artists to hit:
image

image

This artist matching fixed the error of "Eve" 100% matching with "Nevermore", since one was a substring of the word. Now we just grant bonus points per full word match.  Threshold around 80 for now
image

Also another feature:
image
if user artist input isn't that good, it finds based on fuzzy title, locates the exact artist, and uses both user and exact match artist to query against romanization candidates.

## 💬 Additional Comments

Need to test further and revise if needed

### CODE REVIEW

File: ChordKTV/Utils/CompareUtils.cs [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+        );
+
+        float durationDifference = MathF.Abs((queryDuration ?? candidateDuration) - candidateDuration);
+
+        int artistDifference = 0;
+        if (!string.IsNullOrWhiteSpace(artist) && !string.IsNullOrWhiteSpace(candidateArtist))
+        {
+            artistDifference = 100 - Fuzz.Ratio(artist.ToLowerInvariant(), candidateArtist.ToLowerInvariant());
+        }
+        return (int)(fuzzyScore - (durationDifference * durationDifferenceWeight) - (artistDifference * 0.7));
```
Comment (halcdev) [inline ChordKTV/Utils/CompareUtils.cs:31]: Consider making the artist difference weight a configurable param like artistDifferenceWeight = 0.7f for consistency

Comment (darint916) [reply ChordKTV/Utils/CompareUtils.cs]: implemented

**Review by parthivshaji — COMMENTED** [review]
Great work, just update the README as well since I had some stuff about the LRC endpoint which is now outdated

Also, for the search example with wings of fire, LRCLIB has a romanized example with only plain lyrics called "WINGS OF FIRE (TV-mix)" 
image

Why doesn't the search get these plain romanized lyrics? Do you only get romanized lyrics if both plain and synced lyrics exist?

Also, don't forget to rebase/merge main

File: ChordKTV/Utils/KeywordExtractorUtils.cs [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+namespace ChordKTV.Utils;
+
+//partial cuz of stinky regex https://stackoverflow.com/a/78951626
+public partial class KeywordExtractorUtils
+{
+    private static readonly HashSet<string> _stopWords = new(StringComparer.OrdinalIgnoreCase)
+    {
+        "official", "video", "music", "remastered", "live", "ft.", "feat.", "remix",
+        "version", "extended", "edit", "audio", "lyric", "cover", "performance",
+        "mix", "explicit", "radio", "instrumental"
```
Comment (parthivshaji) [inline ChordKTV/Utils/KeywordExtractorUtils.cs:13]: What about stop words with characters like '-' in between? Example "TV-Mix" is pretty common for anime tracks

Comment (darint916) [reply ChordKTV/Utils/KeywordExtractorUtils.cs:13]: Regex deletes all special characters, replaces with space, and then Mix is removed, I just added one for TV, so should resolve 
`[GeneratedRegex(@"[^\w\s]")]`

File: ChordKTV/Services/Service/FullSongService.cs [hunk 3]
```diff
@@ -47,7 +48,7 @@ public FullSongService(ILrcService lrcService, IGeniusService geniusService, ISo
             float? songDuration = (float?)song.Duration?.TotalSeconds;
 
             //TODO: Delete once issue #48 solved
```
[the remark this answers is not in the document]
Comment (darint916) [reply ChordKTV/Services/Service/FullSongService.cs]: done

File: ChordKTV/Services/Api/ILrcService.cs [hunk 4]
```diff
@@ -5,5 +5,5 @@ namespace ChordKTV.Services.Api;
 public interface ILrcService
 {
     // Added "qString" which LRCLIB uses to search for keyword present in ANY fields (track's title, artist name or album name)
```
[the remark this answers is not in the document]
Comment (darint916) [reply ChordKTV/Services/Api/ILrcService.cs]: done

**Review by parthivshaji — DISMISSED** [review]
Good work, it looks fine to me. Anyways we can catch any future issues when we finish #77

**Review by parthivshaji — APPROVED** [review]
yes
